name: p5_1_714220058
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets :
  - images/ulbi.jpg 
  
  fonts:
    - family: AntonSC
      fonts:
        - asset: font/AntonSC-Regular.ttf