name: flutter_application_uts
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0 
  flutter_colorpicker: ^1.1.0
  file_picker: ^8.1.4
  open_file: ^3.5.10
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  
  assets:
    - images/background.jpg
    - images/fotoqin.jpg
    - images/ulbi.jpg
    - images/apa.jpg

  fonts:
    - family: Nabla
      fonts:
        - asset: font/Nabla/static/Nabla-Regular.ttf
    - family: Domine
      fonts:
        - asset: font/Nabla/Domine/static/Domine-Bold.ttf

